services:
  js-backend:
    build:
      context: ./backend
      dockerfile: ../backendDockerfile
    restart: unless-stopped
    init: true
    env_file: ./backend/.env
    # If you have a .env file in ./backend, it will be used for environment variables
    networks:
      - app-network
    ports:
      - "4000:3000"  # Expose backend on host port 4000 (container 3000)

  ts-frontend:
    build:
      context: ./frontend
      dockerfile: ../frontendDockerfile
    restart: unless-stopped
    init: true
    env_file: ./frontend/.env
    # If you have a .env file in ./frontend, it will be used for environment variables
    networks:
      - app-network
    ports:
      - "3000:3000"  # Expose frontend on host port 3000 (container 3000)
    depends_on:
      - js-backend  # Ensure backend is up before frontend starts

networks:
  app-network:
    driver: bridge
